# Generated by Django 5.0.6 on 2024-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_user_delete_vendoruser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(related_name="imuser_set", to="auth.group"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="imuser_set", to="auth.permission"
            ),
        ),
    ]
