# Generated by Django 5.0.6 on 2024-05-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_groups_remove_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IMUser",
        ),
    ]
